# Map 1-based optional input ports to variables
pol <- maml.mapInputPort(1) # class: data.frame

### Bucketing occupation ###
pol$occ_group <- "OTHER"
pol[
  grep(
    "WELDING|WELD|WOOD|CONSTRUCTION|CONTRACTOR|^BUILDER$|^DEVELOPER$|CARPENTER|ROOFER", 
    pol$occupation)
  ,
  ]$occ_group <- "CONSTRUCTION AND EXTRACTION"

pol[
  grep(
    "ESTHETICIAN|NANNY|CLEANER|BARBER|COSMETOLOGIST|MORTICIAN|FLIGHT ATTENDANT|^HAIR$|NAIL|STYLIST|HAIRDRESSER",
    pol$occupation)
  ,
  ]$occ_group <- "PERSONAL CARE AND SERVICE"

pol[
  grep(
    "PEDIATRICS|^LPN$|GASTROENTEROLOGY|PULMONOLOGIST|OPHTHAMOLOGIST|OPHTHALMOLOGY|^OB-GYN$|^PSYCH$|CLINICIAN|PSYCHIATRY|^OBGYN$|ANESTHESIOLOGY|NEONATOLOGIST|^VET$|^DDS$|PHARMACY|ANESTHETIST|PHARMACEUTICALS|NURSING|^OB/GYN$|GASTROENTEROLOGIST|OPTHALMOLOGIST|ENDODONTIST|PATHOLOGIST|PATHOLOGIST|PERIODONTIST|^PHYSCIAN$|ONCOLOGIST|OPTHAMOLOGIST|ANESTHETIST|^NURSE$|OPHTHALMOLOGIST|PHYSICAN|DOCTOR|DENTIST|PHYSICIAN|PHARMACIST|SURGEON|ANESTHESIOLOGIST|VETERINARIAN|^MD$|^RN$|PSYCHOTHERAPIST|ORTHODONTIST|CHIROPRACTOR|OPTOMETRIST|PEDIATRICIAN|CARDIOLOGIST|PSYCHIATRIST|GASTROENTEROLOGY|RADIOLOGY|UROLOGIST|^R.N.$|DERMATOLOGIST|PODIATRIST|^M.D.$", 
    pol$occupation)
  ,
  ]$occ_group <- "HEALTHCARE PRACTITIONERS AND TECHNICAL"

pol[
  grep(
    "WELLNESS|INSTUCTOR|YOUTH|^REAL ESTATE ADVISOR$|^ED$|^PARTNER$|VOCATIONAL|COUNSELOR|COSULTANT|GUIDE|ADVISER|CONSUTLANT|UNIVERSITY|UNIV|COLLEGE|PHD| PROF|TEACHING|HEADMASTER|PROFESOR|SCHOOL|SCHOLAR|PROFESSOR|INSTRUCTOR|ARCHIVIST|COACH|^LIFE COACH$|TUTOR|LECTURER|ACADEMIC|EDUCATION|TEACHER|TRAINER|PRINCIPAL|EDUCATOR|^PROFESSOR$|CONSULTANT|CONSULTING|LIBRARIAN|EDITOR|LECTURER|FACULTY|^DEAN$|ADVISOR|EDUCATION", 
    pol$occupation)
  ,
  ]$occ_group <- "EDUCATION, TRAINING, AND LIBRARY"

pol[
  grep(
    "LEGISLATOR|LEGISLATIVE|BUREAUCRAT|^COUNSEL$|^PUBLIC POLICY$|^GENERAL COUNSEL$|JUSTICE|ATTORNEY|MAGISTRATE|ATTORMEY|LAYWER|ATTONEY|DEFENDER|COURT|^ATTY$|LEGAL|PARALEGAL|JUDGE|LAWYER|LOBBYIST|GOVERNMENT|^LAW$|INVESTIGATOR", 
    pol$occupation)
  ,
  ]$occ_group <- "LEGAL"

pol[
  grep(
    "HOTELS|^HOUSING$|LEASING|FREEHOLDER|^HOUSEKEEPER$|LANDSCAPE|GARDENER|LANDSCAPING|^INNKEEPER$|LANDLORD|LANDSCAPER", 
    pol$occupation)
  ,
  ]$occ_group <- "BUILDING AND GROUNDS CLEANING AND MAINTENANCE"

pol[
  grep(
    "^REALTOR$|DEALER|SALES|APPAREL|RE-SALE|BROKER|TRADER", 
    pol$occupation)
  ,
  ]$occ_group <- "SALES AND RELATED"

pol[
  grep(
    "OWNER|^REAL ESTATE$|^REALTY$|^REAL-ESTATE$|^REALESTATE$|^REAL ESTATE$|^REAL ESTATE DEVELOPMENT$|(HOME()?)?BUILDER|(HOME()?)?DEVELOPER|SUPPLY|BONDSMAN|MORTGAGE|MRKTNG|RETAIL|EXPORTER|BANK|E-COMMERCE|ECOMMERCE|LIASON|SELLER|MERCHANDISER|DISTRIBUTION|WHOLESALE|TRADING|PURCHASING|LENDER|FUND|C. P. A.|INVESTING|FUNDRAISING|ENTREPENEUR|INVESTER|ASSOCIATE|MARKETER|FINANCIER|WHOLESALER|ESTIMATOR|BUYER|^SENIOR ASSOCIATE$|BOOKSELLER|MERCHANT|ASSOCIATE|IMPORTER|DISTRIBUTOR|UNDERWRITING|FINANCE|FUNDRAISER|OPERATIONS|APPRAISER|MARKETING|BANKER|INSURANCE|INVESTOR|ACCOUNTANT|^CPA$|^ANALYST$|^C.P.A$|INVESTMENT|FINANCE|FINANCIAL|^BUSINESSMAN$|^BUSINESSWOMAN$|BANKING|^BUSINESS DEVELOPMENT$|ADVERTISING|TREASURER|INVESTMENTS|BUSINESS|VENTURE|CAPITALIST|INVESTMENT|SHAREHOLDER|^BUSINESS OPERATIONS$",
    pol$occupation)
  ,
  ]$occ_group <- "BUSINESS AND FINANCIAL OPERATIONS"

pol[
  grep(
    "^ENGR$|AEROSPACE|^LAND SURVEYOR$|ENGINEER|ARCHITECT",
    pol$occupation)
  ,
  ]$occ_group <- "ARCHITECTURE AND ENGINEERING"

pol[
  grep(
    "VETRAN|RETIRED|RETIREE|WWII VET|VETREN|^RET$",
    pol$occupation)
  ,
  ]$occ_group <- "RETIRED"

pol[
  grep(
    "SCIENTIST|PSYCHOLOGY|PSYCHOLOGIST|ARBORIST|ENTOMOLOGIST|METROLOGIST|GEMOLOGIST|ARCHEOLOGIST|GENETICIST|OCEANOGRAPHER|R&D|HORTICULTURIST|GEOGRAPHER|HYDROLOGIST|LINGUIST|PHILOSOPHER|TOXICOLOGIST|METEOROLOGIST|BIOTECH|ARCHAEOLOGIST|ECOLOGIST|^PUBLIC HEALTH$|HISTORIAN|HISTORIAN|EPIDEMIOLOGIST|GEOLOGIST|PHYSICIST|ECONOMIST|RESEARCHER|PSYCHOLOGIST|CHEMIST|^ART HISTORIAN$|RESEARCH|BIOLOGIST|INVENTOR", 
    pol$occupation)
  ,
  ]$occ_group <- "LIFE, PHYSICAL, AND SOCIAL SCIENCE"

pol[
  grep(
    "WEBMASTER|TELECOM|^TECH$|WEB |WEB|COMPUTER|^TECHNOLOGIST$|VFX|COMPUTERS|^TECHNOLOGY$|STATISTICIAN|^PROGRAMMER$|SOFTWARE|ACTUARY|^IT$|SOFTWARE|^INFORMATION TECHNOLOGY$|MATHEMATICIAN", 
    pol$occupation)
  ,
  ]$occ_group <- "COMPUTER AND MATHEMATICAL"

pol[
  grep(
    "^AG$|TIMBER|FARM|CATTLE|FEEDER|LOGGER|^BEEKEEPER$|^LUMBER$|FORESTRY|ORCHARDIST|GROWER|CATTLEMAN|^LUMBERMAN$|FISHING|HORSE BREEDER|WILDLIFE|FISHERMAN|RANCHER|FARMER|FARMING|AGRICULTURE|FORESTER", 
    pol$occupation)
  ,
  ]$occ_group <- "FARMING, FISHING, AND FORESTRY"

pol[
  grep(
    "WELFARE|PRIEST|CONSERVATOR|MINISTRY|ALDERMAN|MISSIONARY|UNION|NATION|ADVOCACY|CONSERVATION|^SOCIAL SERVICES$|^CIVIL SERVICE$|TRIBE|ADVOCATE|CHAPLAIN|BISHOP|^CAREGIVER$|^SOCIAL WORK$|CLERGY|CONSERVATIONIST|PASTOR|^SOCIAL WORKER$|VOLUNTEER|^COUNSELOR$|MINISTER|INDIAN TRIBE|MEDIATOR|RABBI|^ACTIVIST$|^PHILANTHROPIST$", 
    pol$occupation)
  ,
  ]$occ_group <- "COMMUNITY AND SOCIAL SERVICE"

pol[
  grep(
    "HR|VERIFIER|ANALYST|BOOKKEEPING|DISPATCHER|AIDE|ORIGINATOR|TELLER|DEMOGRAPHER|EVALUATOR|CONTRACTING|ADJUSTER|REGISTRAR|RESOURCES|SCHEDULER|POLLSTER|DELEGATE|ORGANIZER|COMPLIANCE|SURVEYOR|CARRIER|^SPECIALIST$|EMPLOYEE|SERVANT|AGENT|CASHIER|ERSURVEYOR|CLERICAL|^TRAVEL AGENT$|VACATION|AGENT|^LEGISLATIVE AIDE$|^LETTER CARRIER$|AUCTIONEER|RECEPTIONIST|CLAIMS|WORD|GROCER|ADMIN|ADMINISTRATION|^BOOKKEEPING$|^BOOKKEEPER$|SECRETARY|ADMINISTRATOR|AFFAIRS|WEALTH|^ADMINISTRATIVE ASSISTANT$|STAFF|ACCOUNTING|PLANNER|HOTELIER|CLERK|ASSISTANT|TAX|^HR$", 
    pol$occupation)
  ,
  ]$occ_group <- "OFFICE AND ADMINISTRATIVE SUPPORT"

pol[
  grep(
    "DISABLED|NOT IN WORKFORCE|UNEMPLOYMENT|STUDENT|UNEMPOLYED|UNEMPLOYED|UNEMPLYE|UNEMPLYD|NOT EMPLOYED|NOT-EMPLOYED|^NONE$",
    pol$occupation)
  ,
  ]$occ_group <- "UNEMPLOYED"

pol[
  grep(
    "^CNA$|X-RAY|VETERINERIAN|VETERNERARIANVETERNARIAN|VETERIANARIAN|NURSE|VETERIANRIAN|VETERINARY|HEALER|PHYSICIAL|VACCINE|ORTHOPEDIST|ORTHOTIST|HYGENIST|SONOGRAPHER|PHYSIATRIST|HEALTH|THERAPY|OPTICIAN|DIETICIAN|^HEALTH-CARE$|AUDIOLOGIST|DENTAL HYGIENIST|ACUPUNCTURIST|THERAPIST|PHYSICAL THERAPIST|RADIOLOGIST", 
    pol$occupation)
  ,
  ]$occ_group <- "HEALTHCARE SUPPORT"

pol[
  grep(
    "YARD|VEGETATION|EXTERMINATOR|CRAFTSMAN|CRAFYMAN|^ELECTRICAL$|REPAIR|RECYCLER|CUSTODIAN|LONGSHOREMAN|WASHER|HANDYMAN|HVAC|FOREMAN|^WORKER$|MAINTENANCE|WELDER|LABORER|TECHNICIAN|ELECTRICIAN|^MECHANIC$|PLUMBER", 
    pol$occupation)
  ,
  ]$occ_group <- "INSTALLATION, MAINTENANCE, AND REPAIR"

pol[
  grep(
    "CONTROLLER|OPERATOR|WASTEWATER|TREATMENT|PURIFICATION|WATER POLLUTION|WATER PROGRAM|MECHANIC|STOCKMAN|UTILITY|PACKING|BOTTLER|COAL|MFG|DRILLER|LINEMAN|TEXTILES|OIL|OILFIELD|RECYCLING|AUTOMOTIVE|MINING|ENERGY|LANDMAN|MINER|PETROLEUM LANDMAN|MACHINIST|OIL & GAS|MANUFACTURER|MANUFACTURING|COAL MINER|OIL AND GAS|CONTROLLER", 
    pol$occupation)
  ,
  ]$occ_group <- "PRODUCTION"

pol[
  grep(
    "SELF-EMPLOYED|SELF EMPLOYED|SELF",
    pol$occupation)
  ,
  ]$occ_group <- "SELF-EMPLOYED"

pol[
  grep(
    "VENDING|BEEF|WINE|BARISTA|SERVER|BREWER|FOOD|^WINEMAKER$|RANCH|BARTENDER|BAKER|DAIRYMAN|VINTNER|^CHEF$|CATERER|RESTAURANTEUR|RESTAURATEUR", 
    pol$occupation)
  ,
  ]$occ_group <- "FOOD PREPARATION AND SERVING RELATED"

pol[
  grep(
    "VEHICAL|VEHICLE|VALET| DOT|FERRIES|RAILROAD|SAILOR|MAIL|POST OFFCE|WAREHOUSE|POSTMASTER|DELIVERY|MOVER|EXCAVATOR|SHIPPING|YELLOW CAB|SHIP|AVIATION|TRUCKER|^FLIGHT ATTENDANT$|PILOT|TRANSPORTATION|TRUCKING|DRIVER", 
    pol$occupation)
  ,
  ]$occ_group <- "TRANSPORTATION AND MATERIAL MOVING"

pol[
  grep(
    "SECURITY|COLONEL|LIEUTENANT|COSTOMS|FIREMAN|CRIMINOLOGIST|MARSHAL|DEFENSE|ARMY|VETERAN|MILITARY|MIL DOD|MARINE|IMMIGRA|DETECTIVE|NAVY|TROOPER|POLICE|FIGHTER|SHERIFF|AIR FORCE|FIREFIGHTER|SOLDIER", 
    pol$occupation)
  ,
  ]$occ_group <- "PROTECTIVE SERVICE"

pol[
  grep(
    "DIPLOMAT|COUNCILMEMBER|^COUNCILWOMAN$|HOUSE REP|US GOVT|US GOV|REPRESENTATIVE|^COUNCILMAN$|^SELECTMAN$|ASSEMBLYMAN|CONGRESSWOMAN|ASSEMBLYWOMAN|COUNCILWOMAN|AMBASSADOR|ELECTED OFFICIAL|STATE REP|CONGRESSMAN|CONGRESS|SENATOR|COUNCIL MEMBER|MAYOR|CANDIDATE|COMMISSIONER", 
    pol$occupation)
  ,
  ]$occ_group <- "POLITICIAN"

pol[
  grep(
    "^HOMEMAKER$|^HOME MAKER$|^HOME$|^HOUSE WIFE$|WIFE|WIDOW|^AT HOME$|MOM|MOTHER|HOUSEWIFE",
    pol$occupation)
  ,
  ]$occ_group <- "HOMEMAKER"

pol[
  grep(
    "SPOKESMAN|WRTER|WTITER|WRTIER|VIDEO|VOCALIST|VISUAL|CANTOR|VIOLIST|TELEVISION|PIANIST|SPORTSCASTER|JEWELRY|SPOKESPERSON|VIOLINIST|DOCUMENTARIAN|GALLERIST|JEWLER|CHOREOGRAPHER|ATHLETE|CINEMATOGRAPHER|ANIMATOR|STAGEHAND|FASHION|TOURISM|NUMISMATIST|MUSIC|REPORTER|COLUMNIST|PERFORMER|DANCER|RELATIONS|BROADCASTING|FILM|SPEAKER|PLAYWRIGHT|ILLUSTRATOR|ORGANIST|HOST|POET|VIDEOGRAPHER|POTTER|DECORATOR|NOVELIST|FLORIST|DECORATOR|SINGER|PUBLICIST|ENTERTAINMENT|GOV'T AFFAIRS|CURATOR|BROADCASTER|TALENT AGENT|COMPOSER|PUBLICATION|COMMUNICATION|^PR$|ENTERTAINER|SCULPTOR|WRITER|^PRODUCER$|AUTHOR|DESIGNER|NARRATOR|ACTOR|VOICE|PHOTOGRAPHY|PUBLISHER|MUSICIAN|^ACTOR$|^ARTIST$|TV|WARNER|WEATHERMAN|ACTRESS|JOURNALIST|PUBLISHING|JEWELER|DESIGN|PHOTOGRAPHER|SCULPTOR|PAINTER", 
    pol$occupation)
  ,
  ]$occ_group <- "ARTS, DESIGN, ENTERTAINMENT, SPORTS, AND MEDIA"

pol[
  grep(
    "DIRECTOR OF|^VC$|VICE-CHAIR|VP|MGR|CEO|BOARD|VICE|OFFICER|CHAIRMAN|^CHIEF EXECUTIVE OFFICER$|^AVP$|^DPM$|^C.F.O$|^PM$|^CHARMAN$|EXCECUTIVE|^CPO$|^REL$|^BOSS$|MANGER|EXCUTIVE|^REP$|^SYSTEMS$|^MGT$|STRATEGY|^COB$|FELLOW|^C.I.O.$|LEADER|CHARIMAN|^CAO$|^CMO$|^CCO$|^CFP$|^LOGISTICS$|^C. E. O.$|^MGR$|STRATEGIST|^GOVT AFFAIRS$|TRUSTEE|^BOARD MEMBER$|TRUSTEE|^C.F.O.$|^CHAIR$|^VICE CHAIR$|CHANCELLOR|^GM$|MANAGER|^CEO$|EXECUTIVE|^CFO$|^C.E.O$|DIRECTOR|PRESIDENT|OWNER|CHAIRMAN|MANAGING|MANAGEMENT|FOUNDER|ENTREPRENEUR|EXEC|^CHIEF OPERATING OFFICER$|^VP$|^COO$|^CHAIR$|^CIO$|^SUPERVISOR$|^V.P.$|^FOUNDING PARTNER$|^CTO$|^C.O.O.$|PRESIDENT", 
    pol$occupation)
  ,
  ]$occ_group <- "MANAGEMENT"

maml.mapOutputPort("pol");